version: '3'
services:
  wildfly:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9990:9990"
    command: ["bash", "-c", "chmod +x /opt/startup.sh && /opt/startup.sh"]
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.28
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=jboss
      - MYSQL_USER=jboss
      - MYSQL_PASSWORD=jboss
